modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"

[[mods]]
    modId="sswar"
    version="19.2.1.0"
    displayName="WAR"
    credits=""
    authors="skyjay1"
    description='''Custom WAR events'''

[[dependencies.sswar]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sswar]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sswar]]
    modId="blue_skies"
    mandatory=false
    versionRange="[1.3.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sswar]]
    modId="cosmeticarmorreworked"
    mandatory=false
    versionRange="[1.19.2-v1a,)"
    ordering="NONE"
    side="BOTH"

